Zemoga.BlogEngine/Zemoga.BlogEngine.Web/Controllers/BlogEngineController.cs
using Microsoft.AspNetCore.Mvc;
using Zemoga.BlogEngine.Web.Models;
using Zemoga.BlogEngine.Web.Services.Interfaces;
using Zemoga.BlogEngine.Web.Utilidades;

namespace Zemoga.BlogEngine.Web.Controllers
{
    public class BlogEngineController : Controller
    {

        private readonly IBlogEngineService _BlogEngineService;
        private User UserAuthenticated
        {
            get
            {
                var tokenMessage = HttpContext.Session.GetComplexData<TokenMessage>("TokenMessage");
                return tokenMessage != null && tokenMessage.User.IdUser > 0 ? tokenMessage.User : new User();
            }
            set { }
        }

        public BlogEngineController(IBlogEngineService blogEngineService)
        {
            _BlogEngineService = blogEngineService;
        }

        public IActionResult GetPosts()
        {
            ViewBag.Name = string.Empty;
            var listPosts = UserAuthenticated.Role switch
            {
                Role.Writer => _BlogEngineService.GetPostsByAuthor(UserAuthenticated.UserName),
                Role.Editor => _BlogEngineService.GetPostsByStatus(StatusPost.PendingAproval),
                _ => _BlogEngineService.GetPostsByStatus(StatusPost.Published),
            };
            ViewBag.User = UserAuthenticated;
            return View(listPosts);
        }

        public IActionResult DetailPost(long idPost)
        {
            ViewBag.User = UserAuthenticated;
            var postDetails = _BlogEngineService.GetPostWithComments(idPost);
            ViewBag.CountComments = postDetails.BlogComments.Count;
            return View(postDetails);
        }

        [HttpPost]
        public async Task<IActionResult> DetailPost(BlogComment model)
        {
            model.DateComment = System.DateTime.Now;
            await _BlogEngineService.AddCommentPost(model);
            return RedirectToAction("DetailPost", new { idPost = model .IdPost});
        }

        [HttpPost]
        public async Task<IActionResult> CreatePost(BlogPost model)
        {
            model.PublishedDate = System.DateTime.Now;
            model.Status = "Created";
            await _BlogEngineService.CreatePost(model);
            return RedirectToAction("GetPosts");
        }

        [HttpPost]
        public async Task<IActionResult> EditPost(BlogPost model)
        {
            model.PublishedDate = System.DateTime.Now;
            model.Status = "Edited";
            await _BlogEngineService.UpdatePost(model);
            return RedirectToAction("GetPosts");
        }

        [HttpPost]
        public async Task<IActionResult> SubmitPost(long idPost)
        {
            var post = _BlogEngineService.GetPostById(idPost);
            await _BlogEngineService.SubmitPost(post);
            return RedirectToAction("GetPosts");
        }

        [HttpPost]
        public async Task<IActionResult> PublishPost(long idPost)
        {
            var post = _BlogEngineService.GetPostById(idPost);
            await _BlogEngineService.PublishPost(post);
            return RedirectToAction("GetPosts");
        }

        [HttpPost]
        public async Task<IActionResult> RejectPost(long idPost, string comment)
        {
            var post = _BlogEngineService.GetPostById(idPost);
            await _BlogEngineService.RejectPost(post);

            var blogComment = new BlogComment
            {
                DateComment = System.DateTime.Now,
                Comment = comment,
                IdPost = idPost,
                Author = UserAuthenticated.UserName
            };
            await _BlogEngineService.AddCommentPost(blogComment);
            return RedirectToAction("GetPosts");
        }
    }
}

Zemoga.BlogEngine/Zemoga.BlogEngine.Web/Views/BlogEngine/DetailPost.cshtml
@model Zemoga.BlogEngine.Web.Models.PostDetail


@{
    ViewData["Title"] = "Home Page";
}

<input id="idPostBlog" type="hidden" value="@Model.BlogPost.IdPost" />
<div class="container">
    <div class="row">
        <div id="idBlogPost" class="col-md-8 left-side-sidebar">
            <div class="clearfix mt-40">
                <div class="search-item-content">
                    <h3 class="search-item-caption"><a href="/BlogEngine/DetailPost/@Model.BlogPost.IdPost">@Model.BlogPost.Title</a></h3>

                    <div class="search-item-meta mb-15">
                        <ul class="list-inline">
                            <li class="time">@Model.BlogPost.PublishedDate.ToString("MMMM dd, yyyy").‎</li>
                            <li><a href="#">@ViewBag.CountComments Comments</a></li>
							<li><a href="#">Status: @Model.BlogPost.Status</a></li>
                        </ul>
                    </div>
                    <div>
                        @Model.BlogPost.Content
                    </div>
                </div>
            </div>
        </div>
		<br />
		    @if (ViewBag.User.Role == "Writer")
			{
				@if (@Model.BlogPost.Status != "Published" && @Model.BlogPost.Status != "PendingAproval")
				{
					<div  class="col-md-4">
						<input type="button" id="btnEditPost" class="btn-primary bg-success" value="Edit Post" />  
						<input type="button" id="btnSubmitPost" class="btn-primary bg-success" value="Submit Post" />
					</div>
					<div id="editForm" style="display: none;">
						<form id="formEditPost" asp-controller="BlogEngine" asp-action="EditPost" method="post">
							<input type="hidden" id="IdPost" name="IdPost" value="@Model.BlogPost.IdPost" />
							<input type="hidden" id="Author" name="Author" value="@Model.BlogPost.Author" />
							<div class="row">
								<div class="col-xs-12 col-sm-12">
									<div class="form-group">
										<label>Title</label>
										<input id="Title" name="Title" class="form-input" type="text" placeholder="Write down the Title" value="@Model.BlogPost.Title" required>
									</div>
								</div>
								<div class="col-xs-12">									
									<div class="form-group">
										<textarea id="Content" name="Content" class="form-input" placeholder="Content of the Post" required>@Model.BlogPost.Content</textarea>
									</div>
								</div>
							</div>
							<div class="col-md-4">
								<button id="btnUpdatePost" type="button" class="btn btn-primary pull-right">Update</button>
							</div>

						</form>
					</div>
				}
			}

			@if (ViewBag.User.Role == "Editor" && @Model.BlogPost.Status == "PendingAproval")
			{
				<div  class="col-md-4"> 
					<input type="button" id="btnPublishPost" class="btn-primary bg-success" value="Publish Post" />
					<input type="button" id="btnRejectPost" class="btn-primary bg-danger" value="Reject Post" />
				</div>				
			}
    </div>
</div>

@if(@Model.BlogPost.Status == "Published" || @Model.BlogPost.Status == "Rejected")
{
	<div id="idComments" class="container">
		<div class="be-comment-block">
			<h1 class="comments-title">Comments (@ViewBag.CountComments)</h1>
			@foreach (var comment in Model.BlogComments)
			{
				<div class="be-comment">
					<div class="be-comment-content">
							<span class="be-comment-name">
								<a href="#">@comment.Author</a>
								</span>
							<span class="be-comment-time">
								<i class="fa fa-clock-o"></i>
								@comment.DateComment.ToString("ddd, dd MMM yyy HH:mm:ss ")
							</span>

						<p class="be-comment-text">
							@comment.Comment
						</p>
					</div>
				</div>			
			}
			<form id="formCommentPost" class="form-block" asp-controller="BlogEngine" asp-action="DetailPost" method="post">
				<input type="hidden" id="IdPost" name="IdPost" value="@Model.BlogPost.IdPost" />
				<div class="row">
					<div class="col-xs-12 col-sm-6">
						<div class="form-group fl_icon">
							<input id="Author" name="Author" class="form-input" type="text" placeholder="Your name">
						</div>
					</div>
					<div class="col-xs-12">									
						<div class="form-group">
							<textarea id="Comment" name="Comment" class="form-input" required="" placeholder="Your comment"></textarea>
						</div>
					</div>
					<button id="btnAddComment" type="button" class="btn btn-primary pull-right">Submit</button>
				</div>
			</form>
		</div>
	</div>	
}



@section scripts {
    <script>
        $(document).ready(function () {
            $("#btnEditPost").on('click', function (event) {
                $('#editForm').show();
				$('#idComments').hide();
				$('#idBlogPost').hide();
            });

			$("#btnUpdatePost").on('click', function (event) {
                $('#formEditPost').submit();
            });

			$("#btnAddComment").on('click', function (event) {
                $('#formCommentPost').submit();
            });

			$("#btnSubmitPost").on('click', function (event) {
				var idPost = $('#idPostBlog').val();
				var url = '/BlogEngine/SubmitPost';
               $.post(url, { idPost: idPost}, 
					function(data,status){
					  window.location.href = "GetPosts";
			   });
            });

			$("#btnPublishPost").on('click', function (event) {
				var idPost = $('#idPostBlog').val();
				var url = '/BlogEngine/PublishPost';
               $.post(url, { idPost: idPost}, 
					function(data,status){
					  window.location.href = "GetPosts";
			   });
            });

			
			$("#btnRejectPost").on('click', function (event) {
				var comment = prompt("Write your comment :", "Comment");
				if (comment == null || comment == "") {
				   return;
                } 

				var idPost = $('#idPostBlog').val();
				var url = '/BlogEngine/RejectPost';
               $.post(url, { idPost: idPost, comment: comment}, 
					function(data,status){ window.location.href = "GetPosts"; 
			   });
            });
        });
    </script>
}

Zemoga.BlogEngine/Zemoga.BlogEngine.Web/Views/BlogEngine/GetPosts.cshtml
@model IEnumerable<BlogPost>


@{
    ViewData["Title"] = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <h1>Wellcome @ViewBag.User.Name</h1>
        <div class="col-md-8 left-side-sidebar">
            <div class="clearfix mt-40">
                @if (ViewBag.User.Role == "Writer")
                {
                    <input type="button" id="btnCreatePost" class="btn-primary bg-success" value="New Post" />                    
                }
                <div id="createForm" style="display: none;">
		            <form id="formCreatePost" asp-controller="BlogEngine" asp-action="CreatePost" method="post">
			            <input type="hidden" id="Author" name="Author" value="@ViewBag.User.UserName" />
			            <div class="row">
				            <div class="col-xs-12 col-sm-12">
					            <div class="form-group">
                                    <label>Title</label>
						            <input id="Title" name="Title" class="form-input" type="text" placeholder="Write down the Title" required>
					            </div>
				            </div>
				            <div class="col-xs-12">									
					            <div class="form-group">
						            <textarea id="Content" name="Content" class="form-input" required="" placeholder="Content of the Post" required></textarea>
					            </div>
				            </div>
				            <button type="submit" class="btn btn-primary pull-right">Submit</button>
			            </div>
		            </form>
                </div>
                <ul id="idListPost" class="xsearch-items">
                    @foreach (var post in Model)
                    {
                        <li class="search-item">
                            <div class="search-item-content">
                                <h3 class="search-item-caption"><a href="/BlogEngine/DetailPost?idPost=@post.IdPost">@post.Title</a></h3>
                                <div class="search-item-meta mb-15">
                                    <ul class="list-inline">
                                        <li class="time">@post.PublishedDate.ToString("MMMM dd, yyyy").‎</li>
                                        <li><a href="#">Status: @post.Status</a></li>
                                    </ul>
                                </div>
                                <div>
                                    @post.Content
                                </div>
                            </div>
                        </li>                        
                    }
                </ul>
            </div>
        </div>
    </div>
</div>

@section scripts {
    <script>
        $(document).ready(function () {
            $("#btnCreatePost").on('click', function (event) {
                $('#createForm').show();
                $('#idListPost').hide();
                $('#btnCreatePost').hide();
                
            });
        });
    </script>
}