Zemoga.BlogEngine/Zemoga.BlogEngine.Web/Controllers/AuthenticationController.cs
using Microsoft.AspNetCore.Mvc;
using Zemoga.BlogEngine.Web.Models;
using Zemoga.BlogEngine.Web.Services.Interfaces;
using Zemoga.BlogEngine.Web.Utilidades;

namespace Zemoga.BlogEngine.Web.Controllers
{
    public class AuthenticationController : Controller
    {
        private readonly IAuthenticationServices _AuthenticationServices;

        public AuthenticationController(IAuthenticationServices authenticationServices)
        {
            _AuthenticationServices = authenticationServices;
        }

        public IActionResult Login()
        {
            return View();
        }


        [HttpPost]
        public async Task<ActionResult> Login(LoginModelVM model)
        {
            ViewBag.Error = string.Empty;
            TokenMessage tokenMessage = await _AuthenticationServices.Login(model);
            if (string.IsNullOrEmpty(tokenMessage.Token))
            {
                ViewBag.Error =  "User Not Found";
                return View();
            }
            else
            {
                HttpContext.Session.SetComplexData("TokenMessage", tokenMessage);
            }

            return RedirectToAction("GetPosts", "BlogEngine");

        }

        public IActionResult Logout()
        {
            HttpContext.Session.SetComplexData("TokenMessage", new TokenMessage());
            return RedirectToAction("GetPosts", "BlogEngine");
        }
    }
}

Zemoga.BlogEngine/Zemoga.BlogEngine.Web/Views/Authentication/Login.cshtml
@model Zemoga.BlogEngine.Web.Models.LoginModelVM

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row  vertical-offset">
        <div class="col-md-4">
        </div>
        <div class="col-md-offset-4 col-md-4">
            <section id="loginForm">
                @using (Html.BeginForm("Login", "Authentication", FormMethod.Post, new { role = "form" }))
                {
                    <div class="tittle">@ViewBag.Title</div>
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(m => m.UserName, new { @class = "control-label" })
                        @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.UserName, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Password, new { @class = "control-label" })
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group" >
                        <input type="submit" value="Login" class="btn btn-lg btn-info btn-block" style="margin-top: 10px !important;"/>
                    </div>
                }
                <span style="color: red;">@ViewBag.Error</span>
            </section>
        </div>
    </div>
</div>